#ifndef PAGE_WINDOWS_DEF_H
#define PAGE_WINDOWS_DEF_H

// This had to be outsourced to fix circular dependency problems

enum PAGE_PROTECTION {
	PROT_INVALID,
	NOACCESS,
	READONLY,
	EXECUTABLE,
	EXECUTABLE_READONLY,
	READWRITE,
	COPYONWRITE,
	EXECUTABLE_READWRITE,
	EXECUTABLE_COPYONWRITE,
	NOTCACHABLE_READONLY,
	NOTCACHABLE_EXECUTABLE,
	NOTCACHABLE_EXECUTABLE_READONLY,
	NOTCACHABLE_READWRITE,
	NOTCACHABLE_COPYONWRITE,
	NOTCACHABLE_EXECUTABLE_READWRITE,
	NOTCACHABLE_EXECUTABLE_COPYONWRITE,
	GUARDPAGE_READONLY,
	GUARDPAGE_EXECUTABLE,
	GUARDPAGE_EXECUTABLE_READONLY,
	GUARDPAGE_READWRITE,
	GUARDPAGE_COPYONWRITE,
	GUARDPAGE_EXECUTABLE_READWRITE,
	GUARDPAGE_EXECUTABLE_COPYONWRITE,
	WRITECOMBINE_READONLY,
	WRITECOMBINE_EXECUTABLE,
	WRITECOMBINE_EXECUTABLE_READONLY,
	WRITECOMBINE_READWRITE,
	WRITECOMBINE_COPYONWRITE,
	WRITECOMBINE_EXECUTABLE_READWRITE,
	WRITECOMBINE_EXECUTABLE_COPYONWRITE,
	TARGETSINVALID, // unimplemented
	TARGETSNOUPDATE // unimplemented
};

enum PAGE_STATE {
	STATE_INVALID,
	COMMIT,
	FREE,
	RESERVE
};

enum PAGE_TYPE {
	TYPE_INVALID,
	IMAGE,
	MAPPED,
	PRIVATE
};

#endif /* PAGE_WINDOWS_DEF_H */
